load("@rules_vulkan//glsl:defs.bzl", "glsl_shader")

package(default_visibility = ["//src:__pkg__"])

glsl_shader(
    name = "vert_shader",
    shader = "vertex.vert",
)

glsl_shader(
    name = "frag_shader",
    shader = "fragment.frag",
)
